services:
    #MWoelke\ExampleServiceAnnotationBundle\Controller\ContentElement\ExampleContentElementController:
    #    tags: ['terminal42_service_annotation']
    _defaults:
        autoconfigure: true 
        autowire: true
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]